apiVersion: v1
kind: Service
metadata:
  name: local-one-my-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9376
  selector: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-one-nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels: {}
  template:
    metadata:
      labels: {}
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        ports:
        - containerPort: 80
