apiVersion: someteam.example.com/v1
kind: PolicyTransformer
metadata:
  name: jkulikau
  annotations:
    # config.kubernetes.io/function: |
    #   container:
    #     image: quay.io/justinkuli/scratchpad:policy-transformer
    config.kubernetes.io/function: |
      exec:
        path: ./plugins/transformer
spec:
  chartName: minecraft
