apiVersion: policy.open-cluster-management.io/v1alpha1
kind: PolicyWrapper
metadata:
  name: kitchen-sink
  annotations:
    config.kubernetes.io/function: |
      container:
        image: quay.io/justinkuli/scratchpad:policy-transformer
spec:
  categories: ["CM Configuration Management"]
  controls: ["CM-2 Baseline Configuration"]
  # consolidateManifests to combine all inputs into one policy
  consolidateManifests: false # true by default
  # consolidatePlacements to only create one placement for all policies emitted
  consolidatePlacements: true # false by default
  disabled: false # false by default
  # ignoreNonPolicies to emit non-policy objects unchanged
  ignoreNonPolicies: true # true by default
  placement:
    # ignoreExisting to *always* create a new placement - otherwise, an input placement will be used if found
    ignoreExisting: false # false by default
    clusterSelectors: # For PlacementRule
      {}
      # local-cluster: mine
    labelSelector: # For Placement
      {}
      # local-cluster: mine
      # foobar: ""
  # remediationAction: inform # empty by default
  standards: ["NIST SP 800-53"]
