apiVersion: policy.open-cluster-management.io/v1alpha1
kind: ConfigurationPolicyWrapper
metadata:
  name: config-local-complex
  annotations:
    config.kubernetes.io/function: |
      container:
        image: quay.io/justinkuli/scratchpad:policy-transformer
spec:
  configurationPolicyAnnotations:
    policy.open-cluster-management.io/disable-templates: "true"
  complianceType: "mustonlyhave"
  consolidateManifests: false # multiple configuration policies will be emitted
  evaluationInterval:
    compliant: 30m
    noncompliant: 45s
  metadataComplianceType: "musthave"
  namespaceSelector:
    include: ["default"]
    exclude: ["openshift-*"]
    matchLabels:
      "foobar": "baz"
    matchExpressions:
    - key: "openshift-only"
      operator: "NotIn"
      value: ["true"]
  pruneObjectBehavior: "DeleteAll"
  remediationAction: "enforce"
  severity: "low"
