apiVersion: v1
kind: Namespace
metadata:
  annotations:
    jkulikau.io/kind: ""
  labels:
    openshift.io/cluster-monitoring: "true"
  name: open-cluster-management
---
apiVersion: fake/v1
kind: FakeNode
metadata:
  annotations:
    jkulikau.io/args: /Users/jkulikau/.config/kustomize/plugin/policy.open-cluster-management.io/v1alpha1/fakepolicytransformer/FakePolicyTransformer::/var/folders/m_/k98t8_dd3yggctk0xr8m9b9m0000gn/T/kust-plugin-config-932623390
    jkulikau.io/config-cat: |
      apiVersion: policy.open-cluster-management.io/v1alpha1
      kind: FakePolicyTransformer
      metadata:
        name: jkulikau
      spec:
        foo: bar
    jkulikau.io/function-config-annotation: ""
    jkulikau.io/input-debug: |
      apiVersion: v1
      kind: Namespace
      metadata:
        annotations:
          kustomize.config.k8s.io/id: |
            kind: Namespace
            name: open-cluster-management
            version: v1
        labels:
          openshift.io/cluster-monitoring: "true"
        name: open-cluster-management
      ---
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        annotations:
          kustomize.config.k8s.io/id: |
            group: operators.coreos.com
            kind: OperatorGroup
            name: open-cluster-management
            namespace: open-cluster-management
            version: v1
        name: open-cluster-management
        namespace: open-cluster-management
      spec:
        targetNamespaces:
        - open-cluster-management
      ---
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        annotations:
          internal.config.kubernetes.io/previousKinds: Subscription
          internal.config.kubernetes.io/previousNames: advanced-cluster-management
          internal.config.kubernetes.io/previousNamespaces: open-cluster-management
          kustomize.config.k8s.io/id: |
            group: operators.coreos.com
            kind: Subscription
            name: advanced-cluster-management
            namespace: open-cluster-management
            version: v1alpha1
        name: advanced-cluster-management
        namespace: open-cluster-management
      spec:
        channel: release-2.5
        installPlanApproval: Automatic
        name: advanced-cluster-management
        source: redhat-operators
        sourceNamespace: openshift-marketplace
  name: foo
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    jkulikau.io/kind: ""
  name: open-cluster-management
  namespace: open-cluster-management
spec:
  targetNamespaces:
  - open-cluster-management
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    jkulikau.io/kind: ""
  name: advanced-cluster-management
  namespace: open-cluster-management
spec:
  channel: release-2.5
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
