apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../config-local-simple
- ../config-remote
- ./placement-rule.yaml # will be used
- ./deployment.yaml # will be emitted unchanged
transformers:
- policy-wrapper.yaml
