apiVersion: apps/v1
kind: Deployment
metadata:
  name: other-deployment
spec:
  replicas: 3
  selector:
    matchLabels: {} # set by kustomize
  template:
    metadata:
      labels: {} # set by kustomize
    spec:
      containers:
      - name: other
        image: nginx:1.14.2
        ports:
        - containerPort: 80
