apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../config-local-simple
- ../config-remote
commonAnnotations:
  dir: policy-multi-simple
transformers:
- policy-wrapper.yaml
